### ISSUE TITLE
can-fixture is converting request data to Object

### ISSUE THREAD

**Issue by ines-matos** [canjs/can-fixture#145]
can-fixture is converting request data from Array to Object:

`var xhrData = assign({}, xhrSettings.data || {});
fixtureSettings.data = assign(xhrData, data);`

We would like to keep receiving the data as an Array.

**Comment by justinbmeyer** [comment]
Thanks for reporting. We will try to get someone on this next week. Let us know if you’d like to help.

**Comment by ines-matos** [comment]
Thanks Justin, we already implemented a workaround for that scenario.

**Comment by justinbmeyer** [comment]
```
if(canReflect.isListLike(xhrSettings.data) ) {
  xhrData = assign([], xhrSettings.data);
}
```


```
xhrData = .clone(xhrSettings.data)
```

**Comment by cherifGsoul** [comment]
This issue was already fixed [here](https://github.com/canjs/can-fixture/pull/141) , however I noticed that the conversion from Array to Object is only happened when using `can-ajax` or `jQuery.ajax` but using native `XMLHttpRequest` the array remains the same, this [codepen](https://codepen.io/cherifGsoul/pen/KJPOEG?editors=1011) demonstrate the difference.

**Comment by cherifGsoul** [comment]
I close this issue, because it is not `can-fixture` related, feel free to reopen it to discuss it if you will.
