### ISSUE TITLE
After can-fixture is imported dynamic loading of modules gets broken.

### ISSUE THREAD

**Issue by ilyavf** [canjs/can-fixture#3]
See this app for demo: https://github.com/ilyavf/donejs-app

After _can-fixture_ gets imported, application does not load dynamically imported pages correctly anymore.

IF user goes to "Page Three" which imports can-fixture
AND user tries to go to "Page Two" 
THEN he sees "Loading..." and "Page Two" is not loaded correctly.

In network you can see "/src/page2/page2.js" being fetched, but neither "page2.stache" nor "page2.less".

So far what I can see from debugging is that when can-fixture has _xhr.readyState === 4_ and [self.onreadystatechange()](https://github.com/canjs/can-fixture/blob/master/fixture.js#L346)

``` javascript
        xhr.onreadystatechange = function(){
            if(xhr.readyState === 4) {
                // Copy back everything over because in IE8 defineProperty
                // doesn't work, so we need to make our shim XHR have the same
                // values as the real xhr.
                copyProps(xhr, self, { onreadystatechange: true });

                self.onreadystatechange && self.onreadystatechange();
                self.onload && self.onload();
            }
        };
```

calls in [steal.js](https://github.com/stealjs/steal/blob/master/steal.js#L2611):

``` javascript
      xhr.onreadystatechange = function () {
        if (xhr.readyState === 4) {
          if (xhr.status === 200 || (xhr.status == 0 && xhr.responseText)) {
            load();
          } else {
            error();
          }
        }
      };
```

where xhr.readyState is undefined.

Feels like the problem is somewhere between _copyProps_ and [_defineProperty_](https://github.com/canjs/can-fixture/blob/master/fixture.js#L243)...

**Comment by ilyavf** [comment]
This issue was introduced [with this change](https://github.com/canjs/can-fixture/commit/52fbf86c87e2d36c88cb487c0d5e2c7cd0a0f12a#diff-8b7e2f8f9b664dbebb41e0c7128b01acL230).

**Comment by matthewp** [comment]
Maybe we shouldn't do the copying if the browser supports defineProperty, it's probably not needed in that case.

**Comment by justinbmeyer** [comment]
@matthewp did you resolve this?

**Comment by rjgotten** [comment]
> Maybe we shouldn't do the copying if the browser supports defineProperty

You shouldn't be overwriting native prototypes, period. There's a reason JS devs collectively stopped doing that over a decade ago.

The original idea which implemented them on top of `can.ajax` (and in jQuery's case as an actual prefilter/transport sub-system) was the correct take on a solution: fixtures _should_ just be a layer of glue code sitting inbetween your data-access tier (`can.Model`; `can-connect`; `$.ajax`; etc.) and `XmlHttpRequest` or `Fetch`.

Directly overwriting `XmlHttpRequest` opens you up to a host of scary responsibilities.
You've sofar seen
- `onreadystatechange` events breaking in this issue
- `Content-Type` headers breaking in #31 
- `progress` event support going missing in #10

and there are probably plenty more hiding in the woodwork, all of which could and would affect _any_ unsuspecting code running within a web app or web site, which includes any third party code anywhere, because you overwrite the globally shared native prototype.

If you want to offer a mocked `XmlHttpRequest`, offer it as a `can/util/xhr` module or something instead.

**Comment by matthewp** [comment]
I don't disagree, reimplementing all of XHR is a huge burden and hasn't worked out well. The same problem exists in can-zone.  I wouldn't want to try this with newer APIs like fetch. Luckily XHR is a dead API so all of these bugs will eventually be worked out and new features won't cause further issues.

For clarification, overwriting the prototype isn't the issue here. In fact, if we only had to overwrite the prototype methods (like XHR.prototype.send) then this would be soo much easier. It's only because we overwrite the global constructor and then attempt to mixin all of XHR onto this new fake XHR that we have these problems.

**Comment by justinbmeyer** [comment]
It's fine. Polymer overwrites the DOM methods. Overwriting fetch or getting XHR to work perfect will take time, but it's getting progressively better. 

Fixture, like our design goals for the rest of canjs, is designed to work as independently as possible. Targeting XHR and then fetch is the place to do this.

**Comment by matthewp** [comment]
I'd be very hesitant doing the same thing with fetch that we've done with XHR, it's been a bit of a mess. Asking someone to use `require('fixture-fetch')` or something like that is not asking much.

**Comment by bmomberger-bitovi** [comment]
The fact that we weren't fastidious about mimicking native operations perfectly isn't a strong argument against overwriting the native object in development mode.

It _is_, however, a strong argument for having a full understanding of what can-fixture needs to do for XHRs and fetch() _before_ attempting to implement it.

**Comment by rjgotten** [comment]
> The fact that we weren't fastidious about mimicking native operations perfectly isn't a strong argument against overwriting the native object in development mode.

It is a very strong argument if you consider the fact that a browser is _always_ a hostile, shared environment and your CanJS driven logic will many times co-exist with third parties running their own logic and using those native types as well, in ways you have no control over.

Many times that third-party code will have to run during development as well, so you cannot dismiss that case.
